// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgMNL5toM1suKwRaLxYKS8qR0JWxZre7Y',
    appId: '1:297273493183:web:5523d9dc2d87e39977280a',
    messagingSenderId: '297273493183',
    projectId: 'admin-ef60c',
    authDomain: 'admin-ef60c.firebaseapp.com',
    storageBucket: 'admin-ef60c.appspot.com',
    measurementId: 'G-S65MCT0HKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2-u0EYMWSC2V5kJX-_eOekK_Xpbs2we0',
    appId: '1:297273493183:android:2dd4bf3dba615bc777280a',
    messagingSenderId: '297273493183',
    projectId: 'admin-ef60c',
    storageBucket: 'admin-ef60c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh8-Fe05-S76bvOQr9wSkmNC3eudgL3XQ',
    appId: '1:297273493183:ios:b52ba25f0c57dcf277280a',
    messagingSenderId: '297273493183',
    projectId: 'admin-ef60c',
    storageBucket: 'admin-ef60c.appspot.com',
    iosBundleId: 'com.example.panelAdmin',
  );
}
